
        </div>
        <footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-sm-3">
                        <div class="links">
                            <div class="heading-block">
                                <h4>MVP Ready</h4>
                            </div> <!-- /.heading-block -->
                            <p>Aliquam fringilla, sapien egetferas scelerisque placerat, lorem libero cursus lorem, sed sodales lorem libero eu sapien. Nunc mattis feugiat justo vel faucibus. Nulla consequat feugiat malesuada.</p>
                            <p>Placerat, lorem libero cursus lorem, sed sodales lorem libero eu sapien</p>
                        </div>
                    </div> <!-- /.col -->

                    <div class="col-sm-3">
                        <div class="links">
                            <div class="heading-block">
                                <h4><?php echo $this->translate("Keep In Touch") ?></h4>
                            </div> <!-- /.heading-block -->

                            <ul class="icons-list">
                                <li>
                                    <i class="icon-li fa fa-home"></i>
                                    123 Northwest Way <br>
                                    Las Vegas, NV 89183
                                </li>

                                <li>
                                    <i class="icon-li fa fa-phone"></i>
                                    +1 702 123 4567
                                </li>

                                <li>
                                    <i class="icon-li fa fa-envelope"></i>
                                    <a href="mailto:info@mvpready.com">info@mvpready.com</a>
                                </li>
                                <li>
                                    <i class="icon-li fa fa-map-marker"></i>
                                    <a href="javascript:;"><?php echo $this->translate("View Map") ?></a>
                                </li>
                            </ul>
                        </div>
                    </div> <!-- /.col -->

                    <div class="col-sm-3">
                        <div class="links">
                            <div class="heading-block">
                                <h4><?php echo $this->translate("Connect With Us") ?></h4>
                            </div> <!-- /.heading-block -->

                            <ul class="icons-list">
                                <li>
                                    <i class="icon-li fa fa-facebook"></i>
                                    <a href="javascript:;">Facebook</a>
                                </li>
                                <li>
                                    <i class="icon-li fa fa-twitter"></i>
                                    <a href="javascript:;">Twitter</a>
                                </li>
                                <li>
                                    <i class="icon-li fa fa-soundcloud"></i>
                                    <a href="javascipt:;">Sound Cloud</a>
                                </li>
                                <li>
                                    <i class="icon-li fa fa-google-plus"></i>
                                    <a href="javascript:;">Google Plus</a>
                                </li>
                            </ul>
                        </div>
                    </div> <!-- /.col -->

                    <div class="col-sm-3">
                        <div class="links">
                            <div class="heading-block">
                                <h4><?php echo $this->translate("Stay Updated") ?></h4>
                            </div> <!-- /.heading-block -->
                            <p><?php echo $this->translate("Get emails about new theme launches &amp;  future updates.") ?></p>

                            <form class="form" action="" method="post">
                                <div class="form-group">
                                     <input type="text" placeholder="<?php echo $this->escapeHtmlAttr($this->translate("Email Address")) ?>" required="" value="" name="newsletter_email" id="newsletter_email" class="form-control">
                                </div> <!-- /.form-group -->
                                <div class="form-group">
                                    <button class="btn btn-transparent"><?php echo $this->translate("Subscribe Me") ?></button>
                                </div> <!-- /.form-group -->
                            </form>
                        </div>
                    </div> <!-- /.col -->
                </div>
                <?php echo $this->pageInjectWidget('footer') ?>
                <?php echo $this->pageFooterMenu(5, /* max rows */ 4 /* max columns per row */) ?>
            </div> <!-- /.container -->
        </footer>

        <footer class="copyright">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12">
                        <p class="pull-<?php if ($this->localization()->isCurrentLanguageLtr()): ?>left<?php else: ?>right<?php endif ?>">
                            &copy; <?php echo date('Y') ?> <?php echo $this->applicationSetting('application_site_name') ?>
                        </p>
                        <p class="pull-<?php if ($this->localization()->isCurrentLanguageLtr()): ?>right<?php else: ?>left<?php endif ?>">
                            <?php if ((int) $this->applicationSetting('layout_select')):  ?>
                                <?php $this->declareVars('layoutsList') ?>
                                <?php $this->layoutsList = $this->layoutList()->getLayouts() ?>

                                <?php if (count($this->layoutsList) > 1): ?>
                                    <?php //echo $this->layoutList()->getLayoutsSelectBox('select-layout-link') ?>
                                    <?php echo $this->translate('Layout') ?> - <a href="#" id="select-layout-link"><?php echo $this->escapeHtml($this->layoutList()->getActiveLayout()) ?></a>
                                <?php endif ?>
                            <?php endif ?>
                        </p>
                    </div> <!-- /.col -->
                </div> <!-- /.row -->
            </div>
        </footer>
        <?php echo $this->layoutList()->getLayoutsSelectBox('select-layout-link') ?>
        <?php echo $this->inlineScript() ?>
    </body>
</html>