
        </div>
        <footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="col-sm-3">
                        <div class="heading-block">
                            <h4>MVP Ready</h4>
                        </div> <!-- /.heading-block -->
                        <p>Aliquam fringilla, sapien egetferas scelerisque placerat, lorem libero cursus lorem, sed sodales lorem libero eu sapien. Nunc mattis feugiat justo vel faucibus. Nulla consequat feugiat malesuada.</p>
                        <p>Placerat, lorem libero cursus lorem, sed sodales lorem libero eu sapien</p>
                    </div> <!-- /.col -->
                    <div class="col-sm-3">
                        <div class="heading-block">
                            <h4>MVP Ready</h4>
                        </div> <!-- /.heading-block -->
                        <p>Aliquam fringilla, sapien egetferas scelerisque placerat, lorem libero cursus lorem, sed sodales lorem libero eu sapien. Nunc mattis feugiat justo vel faucibus. Nulla consequat feugiat malesuada.</p>
                        <p>Placerat, lorem libero cursus lorem, sed sodales lorem libero eu sapien</p>
                    </div> <!-- /.col -->
                    <div class="col-sm-3">
                        <div class="heading-block">
                            <h4>MVP Ready</h4>
                        </div> <!-- /.heading-block -->
                        <p>Aliquam fringilla, sapien egetferas scelerisque placerat, lorem libero cursus lorem, sed sodales lorem libero eu sapien. Nunc mattis feugiat justo vel faucibus. Nulla consequat feugiat malesuada.</p>
                        <p>Placerat, lorem libero cursus lorem, sed sodales lorem libero eu sapien</p>
                    </div> <!-- /.col -->
                </div> <!-- /.row -->
            </div> <!-- /.container -->
        </footer>

        <footer class="copyright">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12">
                        <p>Copyright &copy; 2013-15 <a href="javascript:;">Jumpstart Themes</a>.</p>
                    </div> <!-- /.col -->

                </div> <!-- /.row -->
            </div>
        </footer>

        <?php echo $this->inlineScript() ?>
    </body>
</html>