<?php $this->placeholder('content')->captureStart() ?>
    <div class="content">
        <div class="container">
            <?php echo $this->partial('partial/notification') ?>
            <div class="row">
                <div class="col-md-4">
                    <?php echo $this->pageInjectWidget('content-left', $this->page['id']) ?>
                </div>
                <div class="col-md-8">
                    <?php echo $this->pageInjectWidget('content-right', $this->page['id']) ?>
                </div>
            </div>
        </div>
    </div>
<?php $this->placeholder('content')->captureEnd() ?>

<?php echo $this->partial('page/layout-page/_header', [
    'breadcrumb' => $this->breadcrumb, 
    'page' => $this->page
]) ?>

<?php echo $this->placeholder('content') ?>